### PR TITLE
cluster setup

### PR DESCRIPTION
**Pull request by bboozzoo**
Notes on setting up mender in a cluster

@mendersoftware/rndity @eysteins @maciejmrowiec @GregorioDiStefano 

It'd be great if someone tested this with a real cloud provider.

### CODE REVIEW

**Comment by bboozzoo** [comment]
rebased and moved to `/extra/` in the source tree

**Comment by maciejmrowiec** [comment]
what about kubernetes dir, should it end up in extras as well ?

**Comment by bboozzoo** [comment]
yup, pushing another patch

**Comment by bboozzoo** [comment]
merging

**Pull request merged**
