### PR TITLE
Staging alignment

### PR DESCRIPTION
**Pull request by mzedel**

### CODE REVIEW

**Comment by mzedel** [comment]
> @mzedel, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".

@mender-test-bot will you please?

**Comment by mzedel** [comment]
> > @mzedel, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".
> 
> @mender-test-bot will you please?

another round 🙆

**Comment by mzedel** [comment]
> > > @mzedel, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".
> > 
> > 
> > @mender-test-bot will you please?
> 
> another round 🙆

another round 🎡

**Comment by mzedel** [comment]
@lluiscampos the open source job fails even though the test prints `Skipping Open Source test suite for staging testing` - could we `except` the job on staging (I can't find the relevant ci file for this rn)?

**Comment by lluiscampos** [comment]
> @lluiscampos the open source job fails even though the test prints `Skipping Open Source test suite for staging testing` - could we `except` the job on staging (I can't find the relevant ci file for this rn)?

I don't completely understand the error, I am looking deeper into it.

We also have the to integration tests from `TestFileTransferLimits` failing. I'll see if I can figure it out or ping Piotr for help.

**Comment by lluiscampos** [comment]
> > @lluiscampos the open source job fails even though the test prints `Skipping Open Source test suite for staging testing` - could we `except` the job on staging (I can't find the relevant ci file for this rn)?
> 
> I don't completely understand the error, I am looking deeper into it.

See https://github.com/mendersoftware/integration/pull/1389

**Comment by lluiscampos** [comment]
> > We also have the to integration tests from `TestFileTransferLimits` failing. I'll see if I can figure it out or ping Piotr for help.
> 
> The error here is a bit worrying, actually:
> 
> ```
> message = 'access denied: the target file path is outside chroot'
> 
>     def assert_forbidden(rsp, message):
>         try:
> >           assert rsp.status_code == 403
> E           assert 200 == 403
> E             +200
> E             -403
> ```
> 
> Which means that the server returns 200 while the test expected forbidden.
> 
> I launched PR #1390 to better showcase the error, but the problem is in the software stack and not the test.
> 
> Ping @merlin-northern :)

Follow-up from stand up meeting: this is an expected error and we should just ignore.

**Comment by mzedel** [comment]
Thanks @lluiscampos for following up on this! Once #1389 & #1390 are in I'll rebase + trigger another run and then we should be left with only the `TestFileTransferLimits` failure 🤞.

**Comment by mzedel** [comment]
> > > > @mzedel, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".
> > > 
> > > 
> > > @mender-test-bot will you please?
> > 
> > 
> > another round 🙆
> 
> another round 🎡

another round 🏎️

**Comment by mzedel** [comment]
@lluiscampos With the most recent run we now have just `TestFileTransferLimits` (in OS and enterprise) and `TestRemoteTerminal::test_session_recording`(just in enterprise) failing... Since I assume the session recording to be just a spurious error I re-ran the job 🤞
Once that's done and hopefully passing, could you merge despite the failures?

**Comment by mzedel** [comment]
:tada: only `TestFileTransferLimits` failures! @lluiscampos may I invoke your merging powers?

**Pull request merged**
