### PR TITLE
test(fix): add missing services to backend integration tests docker-compose 

### PR DESCRIPTION
**Pull request by kjaskiewiczz**

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr workflows-enterprise/476 --pr deviceauth-enterprise/121

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr workflows-enterprise/476 --pr deviceauth-enterprise/121 --pr integration/2286

**Review by lluiscampos — APPROVED** [review]

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
Already merged in #2284 two weeks ago :+1:

**Pull request closed without merging**
