### PR TITLE
QA-510 test: monitor client tests: sort emails by device date.

### PR DESCRIPTION
**Pull request by merlin-northern**

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please sugar

**Comment by merlin-northern** [comment]
pipeline passed with one known failure: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/743461624

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please sugar

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please sugar sugar

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
