### PR TITLE
Sync staging with master

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by tranchitella** [comment]
@oleorhagen @lluiscampos why is it failing the tests? To me it seems the test is wrong.
Sorry, I'm a bit confused.

**Comment by kacf** [comment]
It is also possible this is related to a bug which I'm working on: The new [N to N mapping](https://tracker.mender.io/browse/QA-344) confuses the tool for certain components. It's not the same failure that [I got](https://gitlab.com/Northern.tech/Mender/integration/-/jobs/1971841574) though. I haven't fully worked out the details of the fix yet, so I can't say for sure if this is related or not.

**Comment by tranchitella** [comment]
> It is also possible this is related to a bug which I'm working on: The new [N to N mapping](https://tracker.mender.io/browse/QA-344) confuses the tool for certain components. It's not the same failure that [I got](https://gitlab.com/Northern.tech/Mender/integration/-/jobs/1971841574) though. I haven't fully worked out the details of the fix yet, so I can't say for sure if this is related or not.

Fixed by https://github.com/mendersoftware/integration/pull/1858

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Pull request merged**
