### PR TITLE
password reset script

### PR DESCRIPTION
**Pull request by mchalski**
Issues: MEN-922

Signed-off-by: mchalczynski <marcin.chalczynski@rndity.com>

as agreed with Eystein, 'password reset' functionality becomes 'nuke the account and recreate via mender ui'. 

related doc: https://github.com/mendersoftware/mender-docs/pull/99

@maciejmrowiec @mendersoftware/rndity

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
nice!

**Comment by kacf** [comment]
Nothing like the brute force approach!

**Comment by estenberg** [comment]
It would be good to have a user confirmation here, in case someone runs the script just to try it out.
"This will reset the user password. Do you want to continue (y/n)?"

**Comment by estenberg** [comment]
Also please note that there is currently a broken docs link until this is merged here: https://docs.mender.io/Troubleshooting/Mender-Server#resetting-administrative-credentials

**Comment by mchalski** [comment]
@estenberg @maciejmrowiec added the yes/no prompt, please review/merge

**Comment by estenberg** [comment]
Thanks!

**Pull request merged**
