### PR TITLE
Bumped Traefik from 2.4 to 2.5

### PR DESCRIPTION
**Pull request by mzedel**
Changelog: title
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by mzedel** [comment]
> @mzedel, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".

🔥 🚀 🎆

**Comment by mzedel** [comment]
> @mzedel, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".

@mender-test-bot  🔥 🚀 🎆

**Comment by tranchitella** [comment]
@mzedel why? Is there a specific feature we need?

**Comment by mzedel** [comment]
Mostly because automatically updating the images in compose files is still not supported by dependabot, but also because of the _ Library change for compress middleware to increase performance_ - hoping that it might also help reducing the load on the gateway (not sure if the TLS termination is already off-loaded)
Apart from that, the local plugins option might be of interest (though so far it's not quite clear if this will be available to everyone)... some more info in the [release notes](https://github.com/traefik/traefik/releases/tag/v2.5.0) & [blog post](https://traefik.io/blog/announcing-traefik-proxy-2-5/)

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
