### PR TITLE
Miscellaneous cleanup in test code

### PR DESCRIPTION
**Pull request by lluiscampos**
Best reviewed commit by commit.

```
commit bc39515d38992feb7514f3c570a137143e02a4c9
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Fri Nov 1 15:02:57 2019 +0100

    Remove AWS S3 tests, fixtures and docker-compose file
    
    These tests are not run in CI. The bucket specified in the file is
    actually empty, so AFAIK they might have never been run.
    
    Furthermore, the value of running few tests on AWS S3 storage is really
    little, keeping in mind that we extensively test MinIO (same API).

commit cae1684b0e971117a9b98203014758118f0a0faa
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Fri Nov 1 17:00:45 2019 +0100

    Remove nightly flag and fix/enable test_image_download_retry_hosts_broken
    
    This test takes very long to run (around 8 minutes on my machine) so it
    was set for "nightly" builds, which we don't have in place in our CI.
    Keeping the test non executed has the obvious risk of not being updated,
    so the test was actually not passing anymore.
    
    Remove the nightly flag and promote this test to "slow".

commit a6a360d6205bfde25b45d7b8e715c5e629ed6e98
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Fri Nov 1 17:04:07 2019 +0100

    Clean-up property from MenderTesting class
    
    Missing from commit 7ec9be0, where the functionality was removed

commit aae0c40f9a2fa956eecece3e9bf236372b3728dd
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Fri Nov 1 17:07:19 2019 +0100

    Fix method get_mender_conf from Artifacts
    
    Not that it matters much, but the method was ignoring the image param
    and using a harcoded image instead.

commit d6712d00de2e946487a9b0f26404ca29210f5d00
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Mon Nov 4 12:00:14 2019 +0100

    Add artifacts sub-url to deployments API
    
    And minor cleanup of superflous pass statement

commit 7de21fa983250311f55a672b236c017f0801ab1b
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Mon Nov 4 12:01:05 2019 +0100

    Fix and use class MongoClient from testutils.infra
    
    The class seems to have been developed but never used. Complete the
    implementation and use it from common.py fixtures.

commit 6b1e3c64e2361900e7d5beb89ac5d60eacafa0eb
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Wed Nov 6 13:22:54 2019 +0100

    Add custom production fixture to test_demo_artifact
    
    Mainly to acquire/release the exposed_ports_lock, which signals the test
    framework that this test uses standard 9000/443 ports... which conflicts
    with other tests ;)
```

### CODE REVIEW

**Comment by lluiscampos** [comment]
Test `test_security.TestSecurity.test_ssl_only` is consistently failing with error:
```
Failed to allocate and map port 9000-9000: Bind for 0.0.0.0:9000 failed: port is already allocated
Failed to allocate and map port 443-443: Bind for 0.0.0.0:443 failed: port is already allocated
...
Traceback (most recent call last):
  File "./production_test_env.py", line 82, in <module>
    assert ret == 0, "failed to start docker-compose"
AssertionError: failed to start docker-compose
```

But I don't really see how it is connected with the changes in this PR...

@kacf Do you see a connection between the change set and the error?

**Comment by kacf** [comment]
Sorry, I can't say that I see the link.

**Comment by lluiscampos** [comment]
Thanks for looking into it. I'll keep thinking of this one...

**Comment by lluiscampos** [comment]
@kacf I think I figure out the problem, see commit 6b1a3c6. The integration tests are running now.

**Comment by kacf** [comment]
> @kacf I think I figure out the problem, see commit 6b1e3c6. The integration tests are running now.

:+1:

**Pull request merged**
