### PR TITLE
QA-233: Add progress tracking to pytest suites

### PR DESCRIPTION
**Pull request by lluiscampos**
Using `pytest-sugar` package

### CODE REVIEW

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
It doesn't seem to work in CI :shrug:

**Comment by oleorhagen** [comment]
> It doesn't seem to work in CI shrug

:'(

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
@oleorhagen Trying with this: https://github.com/Teemu/pytest-sugar/issues/219#issuecomment-786011728 :crossed_fingers:

**Comment by lluiscampos** [comment]
Now it works, do you think is good enough? I am not convinced on how useful it is, because these percentages are not printed after every test, but once on a while for a bunch of tests.

**Comment by oleorhagen** [comment]
Having a look now, but if it is as you say, then I agree :(

**Comment by oleorhagen** [comment]
It seems u are right, this is not what we wanted :'(

**Comment by lluiscampos** [comment]
It was worth a try. Closing.

**Pull request closed without merging**
