### PR TITLE
QA-329 black sigseg workaround

### PR DESCRIPTION
**Pull request by merlin-northern**
Monitoring RBAC test moved to separate file.

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline honey

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline guapo

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline bonito

**Comment by merlin-northern** [comment]
@lluiscampos for your information

**Comment by lluiscampos** [comment]
This doesn't make sense to me :man_shrugging:

**Comment by merlin-northern** [comment]
> This doesn't make sense to me 🤷‍♂️

believe it or not, but without it it failed every time, see the [pipelines in the ticket](https://gitlab.com/Northern.tech/Mender/integration/-/jobs/1541463622#L473) -- but it must have been something temporary, let's keep it here for a while and see it it comes back.

**Comment by merlin-northern** [comment]
> > believe it or not, [...]
> 
> That is the thing: I don't "believe" that by splitting it to a different file we are fixing the issue 😄
> 
> Unless we have a good explanation, I vote against merging this PR, as it makes sense to keep all monitor related tests in one file.

hehe :) right! I thought I had a good explanation and a fix, but now the sigseg is impossible to reproduce. Let's make a deal: if that does not happen again until next QA meeting, I will close this and QA-329 as well.

**Comment by merlin-northern** [comment]
it has not returned, closing this one as we also rejected the ticket.

**Pull request closed without merging**
