### PR TITLE
test: Disconnect containers from network before removing.

### PR DESCRIPTION
**Pull request by merlin-northern**
Ticket: QA-455
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline pretty please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline pretty pretty please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline pretty pretty please please

**Review by oleorhagen — APPROVED** [review]

**Comment by merlin-northern** [comment]
I was clicking around the pipeline, so thats why it seems cancelled, but it passed a couple of times.

**Pull request merged**
