### PR TITLE
tests: use compose file service name and label instead of image name …

### PR DESCRIPTION
**Pull request by bboozzoo**
…when looking up services

When testing locally, the images may use different tags than assumed in tests.
When looking up services, instead of grepping on image/service names, use labels
set up by docker compose. The labels are:
- com.docker.compose.project - project name, i.e. set by -p <..>
- com.docker.compose.service - service name, same name as used in docker-compose
  file

@GregorioDiStefano @mendersoftware/rndity

### CODE REVIEW

**Comment by bboozzoo** [comment]
review anyone? merge?

**Comment by bboozzoo** [comment]
`Changelog` removed and pushed an update.

**Comment by kacf** [comment]
@bboozzoo: Oh, sorry, with removed I meant changed to `Changelog: None`. :-)

**Comment by bboozzoo** [comment]
updated

**Comment by kacf** [comment]
I guess the failing tests are due to the generally broken test state right now.

**Comment by bboozzoo** [comment]
ping anyone, @GregorioDiStefano @mendersoftware/rndity ?

**Comment by GregorioDiStefano** [comment]
let me re-run this in Jenkins

**Comment by GregorioDiStefano** [comment]
@bboozzoo can you take a look? this seems broken

**Comment by bboozzoo** [comment]
rebased & pushed, let's see if this changes anything

**Comment by bboozzoo** [comment]
merge?

**Pull request merged**
