### PR TITLE
docker-compose.compat.yml: Add 3.1 client for test_compat

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :socks:

**Review by kacf — APPROVED** [review]

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :tiger:

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :shark:

**Comment by lluiscampos** [comment]
Thanks @alfrunes 

Tests passed :tada:

**Pull request merged**
