### PR TITLE
test: Add `mender-3.7` to `TestClientCompatibility`

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]

**Review by kacf — COMMENTED** [review]
Don't you need to add or modify something [here](https://github.com/mendersoftware/integration/blob/master/testutils/infra/container_manager/docker_compose_manager.py#L65)?

**Comment by lluiscampos** [comment]
> Don't you need to add or modify something [here](https://github.com/mendersoftware/integration/blob/master/testutils/infra/container_manager/docker_compose_manager.py#L65)?

No, that is a different test: an explicit full rootfs upgrade from v3 to latest.

The `TestClientCompatibility` auto-discovers the compose files. See [this](https://github.com/mendersoftware/integration/blob/master/testutils/infra/container_manager/docker_compose_manager.py#L103) as an starting poing.

**Comment by lluiscampos** [comment]
The failing integration test is unrelated and it has been failing in nightly for few days now. Merging.

**Pull request merged**
