### PR TITLE
test: Additional sleeps around echo on/off in test_session_recording

### PR DESCRIPTION
**Pull request by merlin-northern**
Changelog: None
Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by merlin-northern** [comment]
@kacf maybe lets give it a go? (assuming the pipeline will pass :>)

**Review by alfrunes — APPROVED** [review]
I think only one sleep is needed. I'm pretty sure only the first two sleep commands have any practical effect in this PR since the real problem is receiving input before the terminal process has started. Anyway, approving since I'm pretty sure this will probably fix the spurious errors.

**Comment by merlin-northern** [comment]
> I think only one sleep is needed. I'm pretty sure only the first two sleep commands have any practical effect in this PR since the real problem is receiving input before the terminal process has started. Anyway, approving since I'm pretty sure this will probably fix the spurious errors.

ok thanks for approval, I will monitor that, and let's after a week or so if we can reduce the number of sleeps.

**Pull request merged**
