### PR TITLE
Fix incorrect YAML with multiple keys.

### PR DESCRIPTION
**Pull request by kacf**
Changelog: None

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
@merlin-northern: I think this fails because the useradm-enterprise:master container has never been pushed and it's looking for it. Can you build it manually and push it?

**Comment by merlin-northern** [comment]
> @merlin-northern: I think this [fails](https://mender-jenkins.mender.io/job/mender-builder/4121/label=googlecloud%20&&%20mender_servers/console) because the useradm-enterprise:master container has never been pushed and it's looking for it. Can you build it manually and push it?

makes lots of sense! master is not build because nothing got merged -- I am waiting for review.

**Comment by kacf** [comment]
[Restarted](https://mender-jenkins.mender.io/job/mender-builder/4132/)

**Comment by kacf** [comment]
Hmm, I'm not sure why it fails now. I think you guys will have to dig into this, and just cherry-pick this fix.

**Comment by lluiscampos** [comment]
[Restarted](https://mender-jenkins.mender.io/job/mender-builder/4169/) again after [mender-qa #280](https://github.com/mendersoftware/mender-qa/pull/280) has been merged.

**Comment by lluiscampos** [comment]
This LGTM now. Feel free to rebase and merge.

The only failing test is the TestCreateOrganization, which will be disabled once you rebase on top of latest master.

**Comment by kacf** [comment]
Thanks!

**Pull request merged**
