### PR TITLE
Web/UI deployment test

### PR DESCRIPTION
**Pull request by olehermanse**
Note: There is an issue with xpath in phantom that I need to fix. Tests work for chrome but not phantom.

### CODE REVIEW

**Comment by olehermanse** [comment]
@GregorioDiStefano I'm currently unable to deploy the image downloaded from https://d1b0l86ne08fsf.cloudfront.net/stable/vexpress-qemu/vexpress_release_2.mender using master. Is this expected? I get Error; bad http response.

**Comment by GregorioDiStefano** [comment]
We want to test master, stable is presumed already tested.

Switch to master, pull latest docker containers and use these URLs:

https://d1b0l86ne08fsf.cloudfront.net/stable/vexpress-qemu/vexpress_release_1.mender
https://d1b0l86ne08fsf.cloudfront.net/stable/vexpress-qemu/vexpress_release_2.mender

Nice test, looking forward to incorporating it into the test suite

**Comment by olehermanse** [comment]
Got that working. Currently stuck on creating deployment. Cannot find a sane way to locate the drop downsin selenium. Maybe we need to create some more ids in that form. Any ideas ? @michaelatmender @GregorioDiStefano

**Comment by michaelatmender** [comment]
I can try adding some ids if needed. We are using material-ui components
which are often rendered as several nested divs, so even giving the
component an id doesn't mean that it will apply to the final rendered div
that is actually clicked.

http://stackoverflow.com/a/41482961 This answer suggests looking for text
in the element using XPath, maybe that can help?

**Comment by olehermanse** [comment]
@michaelatmender Yes, that's what I've been doing until now. But I cannot get those drop downs. Even the Selenium IDE (browser plugin). Doesn't record filling out that form properly.

**Comment by michaelatmender** [comment]
https://github.com/mendersoftware/gui/pull/179 - those IDs should help

**Comment by olehermanse** [comment]
@michaelatmender Thanks! Can I get an ID on the "Authorize x devices" button?

**Comment by olehermanse** [comment]
@GregorioDiStefano I just completed the first fully automated deployment using GUI. This test is close to ready. Here's a little checklist of what's done and what's missing:

- [X] Create user
- [X] Login
- [X] Test header menu buttons
- [X] Upload artifact & check result
- [X] Authorize all devices & check result
- [X] Create deployment
- [ ] Wait for deployment to finish and check status
- [ ] Use the mender artifacts downloaded by run.sh
- [ ] Make the test run in phantomJS (and maybe firefox)
- [ ] Make the test run in travis
- [ ] Some clean up of code

Some of the tests are using very specific xpath's that will break if the UI changes significantly. It is however very quick to update the test with new xpaths. @michaelatmender might want to have a look at this. For example, the "Authorize n devices" button could easily have an id. Improving the test to be more robust is harder/more time consuming, so there is a tradeoff here.

**Comment by GregorioDiStefano** [comment]
Finally taking a look at this!

**Comment by olehermanse** [comment]
@GregorioDiStefano Rebased on master now. The checklist of things still needed in my previous post i still up to date.

**Comment by olehermanse** [comment]
@GregorioDiStefano Rebased on master, added gpg signatures, as well as signed off on my commits.

**Pull request merged**
