### PR TITLE
Monitoring: D-Bus expiration pattern scenarios update.

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline really sugar seriously pretty please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline really sugar seriously pretty and sweet please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline really sugar seriously pretty and hard sweet please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline really sugar seriously pretty and hard sweet please with cherry

**Comment by lluiscampos** [comment]
@merlin-northern What about this PR? Is is worth a refresh or close?

**Comment by merlin-northern** [comment]
> @merlin-northern What about this PR? Is is worth a refresh or close?

we do no have full testing around the expiration patterns for D-Bus. I created this PR for have complete testing scenarios. however it turned out that some of the tests around have to be fixed, and since it was done in the spare time, there was not enough of it to finish. D-Bus in general was an add-on to the add-on, so we can decide now:
1. Either create a task to finish the tests
2. drop it and say we do not test expiration of alerts for D-Bus

your opinion?

**Comment by lluiscampos** [comment]
> > @merlin-northern What about this PR? Is is worth a refresh or close?
> 
> we do no have full testing around the expiration patterns for D-Bus. I created this PR for have complete testing scenarios. however it turned out that some of the tests around have to be fixed, and since it was done in the spare time, there was not enough of it to finish. D-Bus in general was an add-on to the add-on, so we can decide now:
> 
>     1. Either create a task to finish the tests
> 
>     2. drop it and say we do not test expiration of alerts for D-Bus
> 
> 
> your opinion?

I think we should do 1 above. This PR can be closed and referenced from the task, so that we can get the code as base inspiration for when to add the test.

**Comment by merlin-northern** [comment]
> > > @merlin-northern What about this PR? Is is worth a refresh or close?
> > 
> > 
> > we do no have full testing around the expiration patterns for D-Bus. I created this PR for have complete testing scenarios. however it turned out that some of the tests around have to be fixed, and since it was done in the spare time, there was not enough of it to finish. D-Bus in general was an add-on to the add-on, so we can decide now:
> > ```
> > 1. Either create a task to finish the tests
> > 
> > 2. drop it and say we do not test expiration of alerts for D-Bus
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > your opinion?
> 
> I think we should do 1 above. This PR can be closed and referenced from the task, so that we can get the code as base inspiration for when to add the test.

https://tracker.mender.io/browse/MEN-5457

**Comment by merlin-northern** [comment]
ok so I close it as we discussed.

**Pull request closed without merging**
