### PR TITLE
Add changelog tag for previous commit 2e51ab0

### PR DESCRIPTION
**Pull request by lluiscampos**
We forgot to add a Changelog in PR #715

### CODE REVIEW

**Comment by lluiscampos** [comment]
What do you think @mzedel ?

**Comment by lluiscampos** [comment]
Okey. I don't have an strong opinion...

My criteria is that this is something facing the user which is broken in the beta and we have fixed for the final, hence a Changelog is appropriate.

What do you think @kacf ?

**Comment by kacf** [comment]
Definitely this is a bugfix (old version requires a workaround, new one doesn't), so I think there should be a changelog.

**Comment by mzedel** [comment]
Having talked to @kacf I understand the point now, so merging...

**Comment by kacf** [comment]
@mzedel: Do you mind making a note about this in [the Enterprise installation guide](https://docs.mender.io/2.2/administration/production-installation#configuring-enterprise)? And create a task targeted for 2.2.0 to revert that again.

**Comment by mzedel** [comment]
This should be https://github.com/mendersoftware/mender-docs/pull/778 and https://tracker.mender.io/projects/MEN/issues/MEN-2846

**Comment by lluiscampos** [comment]
Thanks.

Cherry-picked to 2.2.x on #721

**Pull request merged**
