### PR TITLE
Upgrade Conductor to 1.8.1

### PR DESCRIPTION
**Pull request by maciejmrowiec**
Main changes:
* Correct logging setup to stdout in docker image
* ElasticCache / Redis support
* Image size reduction comming from change of base images of docker to apline linux.
* Minor bug fixes and improvements.
* JSON_TRANSFORM system tasks.

Full change list: https://github.com/Netflix/conductor/compare/v1.7.6...v1.8.1

Changelog: Title

Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
@mendersoftware/rndity can you guys think about any reason not to go for it?

Main things are logging in container is piped to stdout finally, 1.7.7 pipes it to local file. Dramatic size reduction of image which speeds up integration tests (542MB -> 84MB). Support for AWS hosted redis/elasticsearch.

**Comment by maciejmrowiec** [comment]
Having some issues that need to debug, one is bash missing from alpine so need to switch to sh for our scripts, but seem to have problems with starting up, no useful messages.

**Comment by kacf** [comment]
Make sure you are compiling with `CGO_ENABLED=0`, it doesn't work on alpine.

**Comment by maciejmrowiec** [comment]
Thats JAVA app. Go error is from docker itself because entry point was using bash which is not installed.

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano  is there a Jenkins job?

**Comment by GregorioDiStefano** [comment]
DigitalOcean ran out of high CPU droplets again, I manually intervened and started this job...

**Comment by maciejmrowiec** [comment]
Looks like tests passed ;) yeyyy

**Comment by maciejmrowiec** [comment]
Tested upgrade from 1.7.7 (there are no docs provided by conductor guys around upgrades).
Functionality still works, our workflow still works.

Downside: 
It seem we lose history of past jobs, conductor ui seem to not list any execution history from before the upgrade. There is nothing in application log around that so seem like expected behaviour. Not a big deal as decommissioning is all it have been doing so far.

**Pull request merged**
