### PR TITLE
fix: Disable authentication for the new signup endpoint

### PR DESCRIPTION
**Pull request by alfrunes**
Also removes the old deprecated signup endpoint from the route.

### CODE REVIEW

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --fast

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --pr deployments/482 --fast

**Review by kjaskiewiczz — APPROVED** [review]

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --pr deployments/482 --fast

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --pr deployments/482 --fast

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline --pr tenantadm/482 --fast :face_with_spiral_eyes: :

**Pull request merged**
