### PR TITLE
Fix: Unset variable ENTERPRISE_CLIENT_FILES

### PR DESCRIPTION
**Pull request by oleorhagen**
This variable does not exist in 3.0.x

Changelog: None

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Review by kacf — APPROVED** [review]

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by oleorhagen** [comment]
`test_demo_artifact` passed. Merging.

**Pull request merged**
