### PR TITLE
Set the correct tenant CA certificate path for mtls integration tests

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by alfrunes** [comment]
Started a pipeline with mendersoftware/mtls-ambassador#58 here: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/330119388

**Review by tranchitella — APPROVED** [review]

**Comment by lluiscampos** [comment]
Why aren't we strictly reverting this? https://github.com/mendersoftware/integration/pull/1436/files

**Comment by lluiscampos** [comment]
(the build error I think is my half-way branched out release - can be ignored)

**Comment by lluiscampos** [comment]
> (the build error I think is my half-way branched out release - can be ignored)

It should be fine now, I re-started the job

**Pull request merged**
