### PR TITLE
split compose into backend and client parts

### PR DESCRIPTION
**Pull request by bboozzoo**
Move client service to `docker-compose.client.yml`, update README.

@mendersoftware/rndity @GregorioDiStefano @maciejmrowiec

### CODE REVIEW

**Comment by bboozzoo** [comment]
anyone else wants to take a look?

**Comment by GregorioDiStefano** [comment]
@bboozzoo lets wait until @maciejmrowiec takes a look, so this is a pretty fundamental change to our environment.

**Comment by pasinskim** [comment]
I like the change as well, and it might be useful to continue with having separate yaml files for S3 and minio (as @bboozzoo suggested). 

This should come with some corresponding PR in documentation: https://github.com/mendersoftware/mender-docs/blob/master/01.Getting-started/02.Create-a-test-environment/docs.md

**Comment by maciejmrowiec** [comment]
Looks good, definitely step in the right direction!

What do we do with the `up` script? it used to spin up env with client and now it wont if I understand this. How about having option --with-client or something that will load both compose files.

**Comment by bboozzoo** [comment]
Maybe `up` should include a client container by default? @maciejmrowiec @pasinskim 

I don't use this script often (or at all) so I'm ok with client being included in `up` but skipping it in `docker-compose.yml`

**Comment by maciejmrowiec** [comment]
had a brief chat with @eysteins, would be nice for `./up` script start demo environment by default to make it as simple as possible to get going, and later we can have --production flag to get it away

**Comment by bboozzoo** [comment]
Ok, so we should be fine. With latest commits `up` will also start the client.

I guess nobody will be using `up` for production anyway as it's already mangling /etc/hosts.

**Comment by bboozzoo** [comment]
ping?

**Comment by bboozzoo** [comment]
anyone else wants to comment or can we just merge it now?

**Comment by bboozzoo** [comment]
@pasinskim @GregorioDiStefano do you need to update integration tests once this is merged?

**Comment by bboozzoo** [comment]
ping

**Comment by GregorioDiStefano** [comment]
I think you can just merge this, and ill fix whatever breaks with integration

**Comment by bboozzoo** [comment]
Very well, merging

**Pull request merged**
