### PR TITLE
tests: lower connection timeout

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
just testing how much faster tests are when ssh timeout is lower

**Comment by kacf** [comment]
Yes, this is useful. They should not ever time out in theory, and I think that if you hit the key generation window, a reconnect might sometimes be required. Better to not have to wait 3 minutes in that case.

**Comment by GregorioDiStefano** [comment]
precisely what i was thinking

**Comment by GregorioDiStefano** [comment]
merging this, as its only failing due to other spurious fails

**Pull request merged**
