### PR TITLE
2.7.x: Regenerate crypto materials for mTLS testing using a script

### PR DESCRIPTION
**Pull request by lluiscampos**
Porting #1424.

### CODE REVIEW

**Comment by lluiscampos** [comment]
> @lluiscampos, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".

@mender-test-bot :ping_pong:

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
Thanks @tranchitella for revealing the actual problem: the test is not correctly versioned. I have dropped the second cherry-pick and I have pushed the fix here (and I'll do the same for 2.6.x) and I have a modification in the release_tool for preventing this from happening in future releases.

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
