### PR TITLE
release-3.2.0: update the staging client components to match

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by tranchitella — APPROVED** [review]

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Review by lluiscampos — CHANGES_REQUESTED** [review]
Missing update on client side Docker images, like [mender-client-qemu](https://github.com/mendersoftware/integration/blob/staging/docker-compose.client.yml#L8).

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Review by lluiscampos — APPROVED** [review]

**Comment by oleorhagen** [comment]
ignoring failure in `test_demo_artifact`

**Pull request merged**
