### PR TITLE
feat: Upgrade Traefik major version to v3

### PR DESCRIPTION
**Pull request by mzedel**
to go along with https://github.com/mendersoftware/mender-helm/pull/325

### CODE REVIEW

**Comment by mzedel** [comment]
@mender-test-bot start pipeline 🧱

**Comment by mzedel** [comment]
@mender-test-bot start pipeline 🧱 🧱

**Comment by mzedel** [comment]
@mender-test-bot start pipeline 🧱 🧱 🧱

**Comment by mzedel** [comment]
> @mender-test-bot start pipeline 🧱 🧱 🧱 🧱 🧱

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
