### PR TITLE
remove published ports in get_requirements

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Changelog: none
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
@kacf I need this for running upgrade tests, and will only get test requirements using the `--get-requirements` arg

**Comment by kacf** [comment]
This will change behavior for non-upgrade tests though. Can we live with the ports being exposed there?

**Comment by GregorioDiStefano** [comment]
get-requirements is still called, whenever you execute` run.sh`

**Comment by GregorioDiStefano** [comment]
3rd time a charm?

**Pull request merged**
