### PR TITLE
chore: updated traefik to a more recent version

### PR DESCRIPTION
**Pull request by mzedel**
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by mzedel** [comment]
@mender-test-bot start pipeline

**Comment by mzedel** [comment]
Not sure where the test failures stem from...

**Review by alfrunes — APPROVED** [review]

**Comment by tranchitella** [comment]
@mzedel I don't like the backend integration test failure, please don't merge. I'm debugging it locally.

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
