### PR TITLE
Test binding to port 0

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by kacf — APPROVED** [review]
It looks promising to me. I guess the tests don't agree, but I fail to spot why. I remember this stuff was tricky to get right, so small ordering differences may have a large impact. Just a gut feeling from me would be to ensure that changing the order of `systemctl restart mender-reboot-detector` and `listen` has not disturbed anything. I can't tell whether it would, but it's just a hunch. :-)

**Comment by oleorhagen** [comment]
In fact only one `state-script` test failed, so this is looking pretty good actually. 
Yeh, I will re-order the `systemd` and port listener call, just to please the gods of dark test magic, if this keeps failiing :)
Hunches after having done this for a long time, are not to be ignored!

Thx , @kacf :)

**Comment by lluiscampos** [comment]
@oleorhagen Is this PR an alternative to #992? This approach seems cleaner; if it works I vote for closing #992.

**Comment by oleorhagen** [comment]
> @oleorhagen Is this PR an alternative to #992? 

Yes, the preferred one.

> This approach seems cleaner; if it works I vote for closing #992.

A lot cleaner! However, it doesn't seem to work :/

As things are now, I would vote for merging #992 as a hot patch, and then rebase, remove the #992 fix after it is merged, and try and get this working.

**Comment by oleorhagen** [comment]
Pushed a commit ready for review. Let's just give the pipeline one last chance to run.
If it behaves this time also, this will be merged in favour of #992

**Review by kacf — APPROVED** [review]

**Review by lluiscampos — APPROVED** [review]

**Comment by kacf** [comment]
Latest failure:

> Health check for container a6f26c56582e99ae7a0c41e3e6d94e9d39a837d973e8c0372c6a7f3f3749dcef error: context deadline exceeded: unknown

Doesn't look related to this PR if you ask me.

**Comment by oleorhagen** [comment]
Agreed! Merging

**Pull request merged**
