### PR TITLE
Fixing backend-tests logs saving on failed pipelines.

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Review by alfrunes — APPROVED** [review]
Good catch!

**Comment by merlin-northern** [comment]
> Good catch!

thanks for super-sonic review :*

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline sugar pretty please

**Comment by lluiscampos** [comment]
@merlin-northern Thank you! :pray: :love_letter: I had this in my TODO for many weeks now...

**Pull request merged**
