### PR TITLE
Fix: auditlogs backend tests

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
> @tranchitella, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".

@mender-test-bot

**Review by kjaskiewiczz — APPROVED** [review]
looks good
and thanks for fixing

**Comment by tranchitella** [comment]
Manual PR: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/315573683

**Comment by tranchitella** [comment]
Failures in full integration and acceptance tests are unrelated.

**Pull request merged**
