### PR TITLE
Update staging branch to latest stable mender and mender-artifact.

### PR DESCRIPTION
**Pull request by kacf**
Changelog: None

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by tranchitellawfp** [comment]
@kacf no, for reasons unknown to me, they fail in staging.
@lluiscampos is aware of it, AFAIK.

**Comment by tranchitella** [comment]
@kacf no, for reasons unknown to me, they fail in staging.
@lluiscampos is aware of it, AFAIK.

**Comment by kacf** [comment]
Ok, then I will merge as is. I could not spot anything that is obviously from the new client version.

**Comment by lluiscampos** [comment]
> @kacf no, for reasons unknown to me, they fail in staging.
> @lluiscampos is aware of it, AFAIK.

@tranchitella @kacf Nop, they were passing when before my vacation ;) I noticed earlier today and I will follow-up accordingly.

**Pull request merged**
