### PR TITLE
smoke test for minio

### PR DESCRIPTION
**Pull request by mchalski**
minio is the most probable culprit in our integration issues.

add a smoke test to every fixture which verifies that minio is indeed up and serving.

right now a single check is performed on 2 health-check endpoints, exposed by minio itself.
an alternative would be to curl some api endpoint, but this is cleaner (if the healthcheck endpoints actually work).

TODO:
- build timeout/retry logic into smoke tests?
- port some existing smoke tests for conductor to this module (long term)

### CODE REVIEW

**Comment by mchalski** [comment]
unfortunately, all smoke tests pass, even though tests fail...

so it looks like minio is serving for some time at least.

it's TBD if we even want these checks. I say we just close this.

**Comment by merlin-northern** [comment]
then just close it. good try though.

**Comment by merlin-northern** [comment]
no wait. let me try to do something in here, I can use it for a second.

**Comment by merlin-northern** [comment]
can we do the same but also through the storage proxy? i.e.: use https://s3 ?

**Comment by lluiscampos** [comment]
@mchalski should we close this one?

**Comment by tranchitella** [comment]
> @mchalski should we close this one?

Yes, I think so.

**Pull request closed without merging**
