### PR TITLE
chore: remove tests for the old signup end-points

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: None
Ticket: MEN-5377

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr workflows-enterprise/521 --pr useradm-enterprise/660 --pr tenantadm/458

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr workflows-enterprise/521 --pr useradm-enterprise/660 --pr tenantadm/458

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr workflows-enterprise/521 --pr useradm-enterprise/660 --pr tenantadm/458

**Review by kjaskiewiczz — APPROVED** [review]
looks good

**Review by alfrunes — APPROVED** [review]

**Comment by lluiscampos** [comment]
@mender-test-bot cherry-pick to:
* 3.6.x

**Pull request merged**
