### PR TITLE
Dependabot updates

### PR DESCRIPTION
**Pull request by lluiscampos**
#1691, #1692, #1693, #1694, #1695, #1696 and #1697.

### CODE REVIEW

**Comment by lluiscampos** [comment]
Dropping #1693 and #1696.

**Comment by lluiscampos** [comment]
Dropping also #1691 and #1697.

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :frog:

**Review by oleorhagen — APPROVED** [review]
Nice little addition

**Pull request merged**
