### PR TITLE
Remove old kubernetes templates.

### PR DESCRIPTION
**Pull request by estenberg**
Do not longer work and can be confusing. Different templates will now be used for larger scale instead.

### CODE REVIEW

**Comment by merlin-northern** [comment]
@0lmi just FYI the old unused and unmaintained definitions are being removed from integration

**Comment by merlin-northern** [comment]
I have no problem here, @kjaskiewiczz do you use those?

**Comment by 0lmi** [comment]
I never looked on it and never used it, so, it's ok for me.

**Comment by kacf** [comment]
Can you rebase your PR @estenberg? The failures should go away, in theory.

**Comment by estenberg** [comment]
Thanks, rebased.

**Pull request merged**
