### PR TITLE
test: drop the -O option to scp

### PR DESCRIPTION
**Pull request by merlin-northern**
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Review by oleorhagen — CHANGES_REQUESTED** [review]
The `-O` option is needed for the Ubuntu 22 runner, as it defaults to sftp, instead of legacy scp, and we don't have sftp support.

**Comment by oleorhagen** [comment]
Locally, I would suggest a `git smudge` workaround for you here, so you can jsut revert the change locally, and then apply it again when you push :)

**Comment by merlin-northern** [comment]
yeh makes sense.

**Comment by merlin-northern** [comment]
> Locally, I would suggest a `git smudge` workaround for you here, so you can jsut revert the change locally, and then apply it again when you push :)

I was confused as ubuntu 22.04 the only distribution that apparently has this. (that I could find)

**Pull request closed without merging**
