### PR TITLE
Backend integration tests: update to latest pytest

### PR DESCRIPTION
**Pull request by lluiscampos**
```
commit 6fa7d1d28b84357438b2b4684c13ca222314ce75
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Fri Oct 4 09:48:51 2019 +0200

    Set Assertion Rewriting for our common.py file
    
    Some tets, namely test_invalid_tenant_token_added_to_default_account,
    expect and verify asserts happening in common.py. This function tells
    pytest to treat the file as test code and rewrite the asserts.
    
    See https://docs.pytest.org/en/latest/writing_plugins.html#assertion-rewriting
    
    It turned out to be that this is the correct behaviour, while v2.x of
    pytest was having a bug (which we were taking advantage of).
    
    Signed-off-by: Lluis Campos <lluis.campos@northern.tech>

commit 9bbeb42b6955b1dd6a3b2585b2d6a7761aab10b9
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Fri Oct 4 09:53:04 2019 +0200

    Update to latest pytest and fix pycrypto version as well
    
    Now that the test framework is ready for latest pytest, let's update.
    
    Fix pycrypto also, so that we don't rely on Ubuntu packaging for it.
    
    Changelog: None
    
    Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
```

New commit:
```
commit 87a1d56aa74d4c58826086846aeb435bf7d64e2b
Author: Lluis Campos <lluis.campos@northern.tech>
Date:   Thu Oct 17 16:58:28 2019 +0200

    Update backend integ tests image base to Python 3
    
    Arrange also the dependencies in an external file and upgrade now the
    components that were not compatible with Python 3.7 (pytest-html).
    
    Changelog: None
    
    Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
```

### CODE REVIEW

**Comment by alfrunes** [comment]
@lluiscampos; would you mind upgrading to Ubuntu 18.04 for the backend test runner while you're at it?

**Comment by mzedel** [comment]
or directly to an official https://hub.docker.com/_/python image?

**Comment by lluiscampos** [comment]
I will upgrade to Python Docker image and move the dependencies to a requirements.txt, as we were talking in yesterday QA meeting.

I'll wait until the release starts, though.

**Comment by lluiscampos** [comment]
@mzedel @alfrunes ready to review (and merge IMO).

I fixed the image to Python 3.7 and updated the pytest dependencies (namely `pytest-html`).

I first tried with latest Python 3.8, but it seems that Crypto package uses a deprecated call to time.clock(). I guess they will fix that soon...
- Python 3.8 failed run: https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/323972013
- Python 3.9 what's new: https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals

**Comment by alfrunes** [comment]
Perhaps we should migrate from Crypto to python-cryptography which seems to be better maintained?

**Comment by lluiscampos** [comment]
> Perhaps we should migrate from Crypto to python-cryptography which seems to be better maintained?

Perhaps... but not in this task. Feel free to create a QA ticket in JIRA for it.

**Comment by alfrunes** [comment]
No need, already made a PR: #729

**Comment by lluiscampos** [comment]
Superseded by #729. Closing

**Pull request closed without merging**
