### PR TITLE
Beyond beta cherry-picks

### PR DESCRIPTION
**Pull request by maciejmrowiec**

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
travis says signoff is missing but all are double signed

**Comment by kacf** [comment]
This needs to run in internal Jenkins. I have started it [here](https://ci.cfengine.com/job/yoctobuild-pr/593/).

**Comment by kacf** [comment]
> travis says signoff is missing but all are double signed

Yes, there is a whole range of commits by Greg that are incorrectly signed. `GregorioDiStefano <GregorioDiStefano@users.noreply.github.com>` != `Greg Di Stefano <greg.distefano+github@gmail.com>`.

@GregorioDiStefano: How are you able to submit those without getting an error? Are you using rebase button in Github?

**Comment by kacf** [comment]
Alright, we found out that by using squash button and having "keep my email private" setting in Github, Github actually lies, and doesn't submit the commit you posted, but a different one that has a different user name. I would urge people not to use the squash button for this reason, but you can if you make sure that "keep my email private" is *not* set, and that your email in Github settings matches your signoff email.

@GregorioDiStefano is fixing this and resubmitting the pull request.

**Comment by GregorioDiStefano** [comment]
Fixed!

**Comment by kacf** [comment]
Looks like Travis is working now, but this is failing in internal Jenkins. Most likely my fault though, so I'm taking a look now.

**Comment by maciejmrowiec** [comment]
if jenkins is failing why it's not listed in status checks?

**Comment by kacf** [comment]
Damn, it took a lot longer than I expected, but I think I fixed the checksumming issues here: https://github.com/mendersoftware/meta-mender/pull/307. I'll rerun this as soon as that's in.

**Comment by kacf** [comment]
> if jenkins is failing why it's not listed in status checks?

This is against 1.1.x, so automatic Jenkins doesn't run for this one. On Greg's TODO list.

**Comment by maciejmrowiec** [comment]
all good now ?

**Comment by kacf** [comment]
Rerunning [here](https://ci.cfengine.com/job/yoctobuild-pr/599).

**Comment by kacf** [comment]
All good.

**Pull request merged**
