### PR TITLE
staging: Update from master + fix deviceauth-enterprise setup [resubmit]

### PR DESCRIPTION
**Pull request by lluiscampos**
Resubmitting #1728 after fixing tests in #1729.

### CODE REVIEW

**Comment by lluiscampos** [comment]
> Resubmitting #1728 after fixing tests in #1729.

In case is not clear,

This PR updates staging from latest master and brings two fixes:

* staging: Fix deviceauth-enterprise setup
    * component-maps.yml: Set release_component to false in OS flavor
    * git-versions.yml: Comment out the OS flavor
    * docker-compose files: use correct image for mender-device-auth


* staging: Set correct git version for devicemonitor

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :basecamp:

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :pray:

**Review by tranchitella — APPROVED** [review]

**Comment by lluiscampos** [comment]
Test failure `TestCreateArtifactEnterprise::test_create_artifact` is pre-existing. Merging.

**Pull request merged**
