### PR TITLE
Change mongo definitions to map the correct path

### PR DESCRIPTION
**Pull request by mterwoord**
Change mongo definitions to map the correct path. 
/data is being mapped, but /data/db needs to.

### CODE REVIEW

**Comment by 0lmi** [comment]
Looks good to me.

**Comment by mirzak** [comment]
Please check https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md for some formalities. 

What is missing is the sign off and the changelog entry in you commit message, for this case it think it is appropriate to add:

     Changelog: Title

That is why the test failed :)

**Comment by 0lmi** [comment]
Sorry, my bad, didn't see the comment.

**Comment by kacf** [comment]
@0lmi, @mirzak: Also, keep in mind that integration builds from externals must be started manually. I started one just now.

**Comment by maciejmrowiec** [comment]
hi @mterwoord, thanks for bringing this issue to our attention!
You should be aware that we are in the process of changing how we organise mongo for next release. We are going to consolidate all databases in single db server instance instead, there is a PR opened https://github.com/mendersoftware/integration/pull/500

**Comment by mterwoord** [comment]
Any eta on a release date for this next release?

If that's "soon", I'll hold on doing things.

**Comment by maciejmrowiec** [comment]
We are planning for September

**Comment by mterwoord** [comment]
In the meantime, what steps do I need to take, to get this PR in?

**Comment by oleorhagen** [comment]
Still can't see that you have added the Changelog and signoff

**Comment by oleorhagen** [comment]
That is just fine :)

**Comment by oleorhagen** [comment]
Then I will rerun the tests, and if they pass, we are good to go to if @0lmi still agrees?

**Comment by mterwoord** [comment]
There we go.

**Comment by oleorhagen** [comment]
nice. waiting for the tests to pass, and  @0lmi to approve, and we are good to go.

**Pull request merged**
