### PR TITLE
Revert "generate new keys using keygen utility"

### PR DESCRIPTION
**Pull request by maciejmrowiec**
Reverts mendersoftware/integration#152

Breaks builds, reverting.

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
Reverting only integration setup part, keeping new keys in client repo, once we get new version on qemu client using new keys available, revert the revert to get it synced.

**Comment by maciejmrowiec** [comment]
@eysteinsm @GregorioDiStefano  ^^

**Comment by estenberg** [comment]
Sorry about that, I was not aware that it would take that long to "sync" these changes.
To that end I can not comment much on this.

**Comment by kacf** [comment]
Normally it doesn't take that long, but because of the recent Yocto breakages, the client has been lagging behind for a long time. However, today it looks like we might finally be getting back on track.

**Comment by maciejmrowiec** [comment]
not applying anymore, client did catch up now

**Pull request closed without merging**
