### PR TITLE
Cherry-pick fixes to 3.3.x

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Review by 0lmi — APPROVED** [review]
LGTM! Huge help for the team with having it done! 👍

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr useradm/320

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr useradm/320

**Pull request merged**
