### PR TITLE
added selenium to requirements.txt

### PR DESCRIPTION
**Pull request by oleorhagen**
added selenium to requirements.txt

Signed-off-by: Ole Petter <ole.orhagen@cfengine.com>

### CODE REVIEW

**Comment by kacf** [comment]
If you make `added selenium to requirements.txt` the title instead, the message becomes shorter, and it's easier to see in the log afterwards. Two for one! :-)

**Comment by kacf** [comment]
>  oleorhagen changed the title from fixup to added selenium to requirements.txt

I mean in the commit. The PR title is not visible in the commit message afterwards.

**Comment by oleorhagen** [comment]
@kacf if u don't have anymore complaints, I will merge this today

**Comment by oleorhagen** [comment]
shit, I always forget that. Now it should be good

**Pull request merged**
