### PR TITLE
Add workflows enterprise images to the docker composition

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Comment by lluiscampos** [comment]
> Almost ;) Missing update [here](https://github.com/mendersoftware/integration/blob/master/extra/release_tool.py#L166).

And a related PR in `mender-qa`. See https://github.com/mendersoftware/mender-qa/pull/367/files

**Comment by tranchitella** [comment]
Here we are:
https://github.com/mendersoftware/mender-qa/pull/372

**Comment by lluiscampos** [comment]
This PR seems to have broken the master integration repo (see latest nightly [here](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/463485141)). I cannot see a successful run of the Pipeline here, didn't we run it?

**Comment by lluiscampos** [comment]
> This PR seems to have broken the master integration repo (see latest nightly [here](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/463485141)). I cannot see a successful run of the Pipeline here, didn't we run it?

I don't know exactly what the problem is: if fails checking the number of services up while the number of expected services for enterprise (I think!) is correct. But I suspect it is related to the fact that launching the enterprise environment now creates two networks: `integration_mender` and `integration_default`. Maybe this gives you a clue?

**Comment by tranchitella** [comment]
@lluiscampos @merlin-northern the PR is fine, I believe the issue is that workflows-enterprise is not starting up properly:

```
[gw1] TestMultiTenancyEnterprise__test_multi_tenancy_deployment -- 2020-03-08 09:15:49,087 [INFO]: >> CONTAINER ID        IMAGE                                                       COMMAND                  CREATED             STATUS                     PORTS               NAMES
[gw1] TestMultiTenancyEnterprise__test_multi_tenancy_deployment -- 2020-03-08 09:15:49,087 [INFO]: >> aa624dfe326a        registry.mender.io/mendersoftware/workflows-enterprise:pr   "/usr/bin/workflows-…"   7 minutes ago       Exited (1) 7 minutes ago                       mender7447670_mender-workflows_1
[gw1] TestMultiTenancyEnterprise__test_multi_tenancy_deployment -- 2020-03-08 09:15:49,087 [INFO]: >> 95d0448d154c        registry.mender.io/mendersoftware/workflows-enterprise:pr   "/usr/bin/workflows-…"   8 minutes ago       Exited (1) 8 minutes ago                       mender6213218_mender-workflows_1
[gw1] TestMultiTenancyEnterprise__test_multi_tenancy_deployment -- 2020-03-08 09:15:49,087 [INFO]: >>
```

I'll have a look at it tomorrow (early) morning.

**Comment by tranchitella** [comment]
@lluiscampos this should fix it, waiting for the test results:
https://github.com/mendersoftware/integration/pull/839

**Pull request merged**
