### PR TITLE
test: retry on composition stop.

### PR DESCRIPTION
**Pull request by merlin-northern**
Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline pretty please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline pretty sugar please

**Comment by merlin-northern** [comment]
@kacf pinging you as the BM for this week. this happened on Saturday, and I believe this is an imprvement.

**Review by kacf — APPROVED** [review]
👍

**Comment by lluiscampos** [comment]
> (...) this happened on Saturday, 

@merlin-northern Was it the same kind or error as reported in [QA-455](https://tracker.mender.io/browse/QA-455)? If so, we can close the bug report :innocent:

**Comment by merlin-northern** [comment]
> > (...) this happened on Saturday,
> 
> @merlin-northern Was it the same kind or error as reported in [QA-455](https://tracker.mender.io/browse/QA-455)? If so, we can close the bug report 😇

I believe ti is exactly that.

**Pull request merged**
