### PR TITLE
Use backend integration test image

### PR DESCRIPTION
**Pull request by mzedel**
needs mendersoftware/mender-test-containers#97 to be merged & ci run to be complete

### CODE REVIEW

**Comment by lluiscampos** [comment]
Can we please remove the`Dockerfile` from here?

**Comment by mzedel** [comment]
> Can we please remove the`Dockerfile` from here?

Argh right thanks! Removed, same as the python requirements & the dependabot entries 👌

**Review by lluiscampos — APPROVED** [review]

**Comment by mzedel** [comment]
@mender-test-bot start pipeline 🤞

**Comment by mzedel** [comment]
> @mender-test-bot start pipeline 🤞

**Review by oleorhagen — APPROVED** [review]

**Comment by mzedel** [comment]
> > @mender-test-bot start pipeline 🤞

**Comment by mzedel** [comment]
> > > @mender-test-bot start pipeline 🤞

**Pull request merged**
