### PR TITLE
MEN-2206: Statistics generator

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by kacf** [comment]
Here is some sample output:

```
Developers with the most changesets
Marcin Chalczynski         102 (37.0%)
Krzysztof Jaskiewicz        63 (22.8%)
Kristian Amlie              35 (12.7%)
Michael Clelland            34 (12.3%)
Maciej Mrowiec               9 (3.3%)
Alf-Rune Siqveland           6 (2.2%)
Ole Petter Orhagen           6 (2.2%)
Don Cross                    5 (1.8%)
Marcin Pasinski              4 (1.4%)
Eystein Måløy Stenberg     4 (1.4%)

Developers with the most changed lines
Michael Clelland          9811 (44.1%)
Marcin Chalczynski        4978 (22.4%)
Krzysztof Jaskiewicz      3492 (15.7%)
Kristian Amlie            2145 (9.6%)
Alf-Rune Siqveland        1184 (5.3%)
Don Cross                  186 (0.8%)
Ole Petter Orhagen         180 (0.8%)
Tobias Klauser              56 (0.3%)
Mirza Krak                  55 (0.2%)
Eystein Måløy Stenberg    47 (0.2%)

Developers with the most lines removed
Kristian Amlie             304 (4.7%)
Tobias Klauser              51 (0.8%)
Eystein Måløy Stenberg    28 (0.4%)

Developers with the most signoffs (total 280)
Marcin Chalczynski         102 (36.4%)
Krzysztof Jaskiewicz        63 (22.5%)
Kristian Amlie              36 (12.9%)
Michael Clelland            34 (12.1%)
Maciej Mrowiec               9 (3.2%)
Ole Petter Orhagen           7 (2.5%)
Alf-Rune Siqveland           6 (2.1%)
Don Cross                    5 (1.8%)
Eystein Måløy Stenberg     4 (1.4%)
Marcin Pasinski              4 (1.4%)

Developers with the most reviews (total 0)

Developers with the most test credits (total 0)

Developers who gave the most tested-by credits (total 0)

Developers with the most report credits (total 0)

Developers who gave the most report credits (total 0)

Top changeset contributors by employer
RnDity                     165 (59.8%)
Northern.tech              103 (37.3%)
cosinekitty@gmail.com        5 (1.8%)
Amarula Solutions            1 (0.4%)
jgitlin@goboomtown.com       1 (0.4%)
tklauser@distanz.ch          1 (0.4%)

Top lines changed by employer
Northern.tech             13514 (60.8%)
RnDity                    8470 (38.1%)
cosinekitty@gmail.com      186 (0.8%)
tklauser@distanz.ch         56 (0.3%)
Amarula Solutions            2 (0.0%)
jgitlin@goboomtown.com       1 (0.0%)

Employers with the most signoffs (total 280)
RnDity                     165 (58.9%)
Northern.tech              107 (38.2%)
cosinekitty@gmail.com        5 (1.8%)
tklauser@distanz.ch          1 (0.4%)
Amarula Solutions            1 (0.4%)
jgitlin@goboomtown.com       1 (0.4%)

Employers with the most hackers (total 16)
Northern.tech               10 (62.5%)
RnDity                       2 (12.5%)
cosinekitty@gmail.com        1 (6.2%)
tklauser@distanz.ch          1 (6.2%)
Amarula Solutions            1 (6.2%)
jgitlin@goboomtown.com       1 (6.2%)
```

We would obviously remove some of the empty sections that are only relevant for kernel development, which is where this script comes from. The script doesn't allow turning it off though, so I included it above to get the right picture.

**Comment by kacf** [comment]
@estenberg

**Comment by kacf** [comment]
Nice to see that in top ten contributors to lines changed, there are two external contributors!

**Comment by mirzak** [comment]
Nice, these stats are from the Mender client right?

**Comment by kacf** [comment]
No, they are from all repos combined, except meta-mender and mender-convert.

**Comment by estenberg** [comment]
Looks really cool, but why did you decide to not include meta-mender and mender-convert?
Today contributions to meta-mender are quite frequent (compared to other repos) and I expect the same to happen for mender-convert.

**Comment by estenberg** [comment]
Also, is mender-docs included? I am not sure if it should be (I don't think that is expected - a doc line is much "cheaper" to write than a code line).

**Comment by kacf** [comment]
> Looks really cool, but why did you decide to not include meta-mender and mender-convert?

Both have releases that are not tied to integration, so the release-tool (which is the basis of the combination) doesn't know about them. For meta-mender it makes sense, because it has a different schedule, and its own entries in the changelog. For mender-convert I suppose there is less reason for that, since we will always release them together.

I think the simplest approach would be to give it the ability to generate statistics from more than one source, so you could ask it to generate statistics for integration (including all sub repos), mender-convert and meta-mender together. Or only one of them in the cases where the releases don't coincide (which is often the case for meta-mender).

My understanding is that we do want to include the statistics in every changelog update, correct?

> Also, is mender-docs included? I am not sure if it should be (I don't think that is expected - a doc line is much "cheaper" to write than a code line).

No. Mender-docs is tricky, because it doesn't have any releases. How do you decide on the range you want to generate statistics for? We could potentially make it time based, but due to the mechanics of Git, it would be somewhat inaccurate. This will be mostly a matter of convention; how we run the tool; since it uses Git ranges directly. Should this be included as well?

**Comment by estenberg** [comment]
Makes sense. A few comments:

* Yes, would be great to have in each changelog update
* Could we generate for meta-mender and mender-convert separately? Doing it as supporting multiple sources would also work, I think (but then the tags would be different).

The purpose is to give credit to those who helped develop any part of Mender, this is why it would be great to somehow include the stats for meta-mender and mender-convert at release time as well.

For meta-mender it probably makes sense to keep it independent as the releases are separate.

**Comment by kacf** [comment]
> Could we generate for meta-mender and mender-convert separately? Doing it as supporting multiple sources would also work, I think (but then the tags would be different).

Absoluty! And this is actually easier, and will work with what I already posted. Maybe we'll start with that then, since it is the simplest. So statistics wise, both meta-mender and mender-convert will have independent statistics, but we can of course post them together in the same release announcement.

I don't think I will include mender-docs for the moment then, unless you have a strong desire that we should. We can always improve on that later.

**Comment by estenberg** [comment]
Sounds great!

**Pull request merged**
