### PR TITLE
MEN-5024: Check that migration to new server works.

### PR DESCRIPTION
**Pull request by kacf**
Plus fix the existing test which passed incorrectly.

### CODE REVIEW

**Comment by kacf** [comment]
@mender-test-bot start pipeline

**Comment by kacf** [comment]
Both failures are in unrelated backend tests.

**Review by lluiscampos — APPROVED** [review]
The second commit looks good :+1: 

The first one is very hard for me to review... but "it makes sense".

Very good catch, by the way. Thank you.

**Comment by kacf** [comment]
> The first one is very hard for me to review... but "it makes sense".

Yes, it's essentially a rewrite, or "re-copy". I guess that if something's wrong there, I can just blame one of the backend devs! 🙂

**Pull request merged**
