### PR TITLE
test: no exceptions need to be made for staging when listing all

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by tranchitella — APPROVED** [review]

**Review by lluiscampos — CHANGES_REQUESTED** [review]
This does not seem correct to me: in `integration/staging` the OS backend repos should not exist.

**Comment by lluiscampos** [comment]
I am looking more into it. I just quickly blocked it for you not to merge it too quick. Let me see what is going on :eyes:

**Comment by oleorhagen** [comment]
> I am looking more into it. I just quickly blocked it for you not to merge it too quick. Let me see what is going on eyes

Sure, thx

**Review by lluiscampos — APPROVED** [review]
You are right, sorry. It is correct :+1:

**Pull request merged**
