### PR TITLE
feat: change inventory redis configuration

### PR DESCRIPTION
**Pull request by kjaskiewiczz**

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr inventory-enterprise/465 --pr useradm-enterprise/724

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr inventory-enterprise/465 --pr useradm-enterprise/724 --pr deviceauth-enterprise/pull/221

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr inventory-enterprise/465 --pr useradm-enterprise/724 --pr deviceauth-enterprise/pull/221

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --fast --pr inventory-enterprise/465 --pr useradm-enterprise/724 --pr deviceauth-enterprise/pull/221

**Review by alfrunes — APPROVED** [review]

**Pull request merged**
