### PR TITLE
Make integration master point to master service images.

### PR DESCRIPTION
**Pull request by maciejmrowiec**
Signed-off-by: Maciej Mrowiec <mrowiec.maciej@gmail.com>

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
FYI: intending to point lastest into latest production releases (moved manually), pointing master integration explicitly towards master images

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano any ideas why this would be failing?
BTW this not getting in may disrupt other builds as `latest` docker tag is not updated anymore only master is

**Comment by GregorioDiStefano** [comment]
we are matching only "mendersoftware/api-gateway" and by default, this will only match "latest" 
we need to add an argument here to specify exactly which tag. 

i can fix tomorrow morning

**Pull request merged**
