### PR TITLE
dependabot: docker and docker-compose

### PR DESCRIPTION
**Pull request by lluiscampos**
#1313 and #1314.

### CODE REVIEW

**Comment by lluiscampos** [comment]
> @lluiscampos, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".

@mender-test-bot just do it :athletic_shoe:

**Comment by lluiscampos** [comment]
Rebased on top of master to retry mender-docs tests. But I won't re-run the full pipeline (all jobs passed in previous run)

**Comment by lluiscampos** [comment]
> #1313 and #1314.

#1320 supersedes #1313.

Re-running tests

**Comment by lluiscampos** [comment]
> @lluiscampos, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".

@mender-test-bot ack :robot:

**Comment by kacf** [comment]
> mender-test-bot ack robot

I have seen lots of these, and I don't understand. Does the bot accept any string?

**Comment by lluiscampos** [comment]
> > mender-test-bot ack robot
> 
> I have seen lots of these, and I don't understand. Does the bot accept any string?

Hehe. It is an internal joke (with myself) that I do all the time. If you quote the bot message, it already contains the command "start pipeline", then it only lacks the mention...

**Comment by kacf** [comment]
Aaaah! Haha, I should have spotted that!

**Pull request merged**
