### PR TITLE
Changelog: Update conductor to 1.7.7

### PR DESCRIPTION
**Pull request by maciejmrowiec**
Region in config has now validation, needed to switch to correct AWS region instead "dummy".

New 1.7.7 images are pushed to docker hub.

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
@mendersoftware/rndity 

tested with demo env
build and pushed images to dockerhub from 1.7.7 tag,
need to sync fork with upstream in another pr

**Comment by GregorioDiStefano** [comment]
@maciejmrowiec please rebase this

**Comment by maciejmrowiec** [comment]
done

**Comment by maciejmrowiec** [comment]
@GregorioDiStefano @bboozzoo should we include this in 1.2 release or skip ?

**Pull request merged**
