### PR TITLE
Reduce output verbosity and include login URL link.

### PR DESCRIPTION
**Pull request by estenberg**
Before:

```
Starting the Mender demo environment...
Creating network "integration_mender" with the default driver
Creating integration_mender-mongo_1         ... done
Creating integration_minio_1                ... done
Creating integration_mender-redis_1         ... done
Creating integration_mender-elasticsearch_1 ... done
Creating integration_mender-gui_1           ... done
Creating integration_storage-proxy_1        ... done
Creating integration_mender-conductor_1     ... done
Creating integration_mender-inventory_1     ... done
Creating integration_mender-device-auth_1   ... done
Creating integration_mender-deployments_1   ... done
Creating integration_mender-useradm_1       ... done
Creating integration_mender-api-gateway_1   ... done
Waiting for the useradm service to start up...
Creating a new user...
9e5ce92d-7e4f-4d09-80aa-baa42478dd14
New user created.
****************************************

Username: mender-demo@example.com
Login password: Ve8fLprmZcfc

****************************************
Please keep the pAfterassword available, it will not be cached by the login script.
Getting JWT Token...
JWT token:  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjY1MTI1NzMsImp0aSI6ImJmYzAwZTkyLWJkMGMtNDk2Ny05MTFhLTg1NjkwZTQ3MTFiYyIsImlzcyI6Im1lbmRlci51c2VyYWRtIiwic3ViIjoiOWU1Y2U5MmQtN2U0Zi00ZDA5LTgwYWEtYmFhNDI0NzhkZDE0Iiwic2NwIjoibWVuZGVyLioiLCJtZW5kZXIudXNlciI6dHJ1ZX0.YY5Br4_gj0uWtW2X6g3PNDE0f6OYWaWTb5JnIynFQE_gGCA70kRPIpUgYoyx2T3QiWOvk6aBy6HFDd9yoGycCcwOFEyMN9RSc0YKRCGzAmkIvaqLayCclU5X5xIRUgpyNGtWxxeaJjS6B0db3GOQrhPmnn-gnWy_E7uEhAnfe1RDsRUKwMRFnBiYmHALRgu9YBHW14RV9PCp1Nt4SYJvdm8XogEW5JElQ3epmwTp-vozZbeXh-_rc3F3G_J-G6ElacfgO6rC1Y1N7-kK1h9GFmQ3JcnVPRSyW-niQg1X4_uYVQEJZrVpmc5RujtO9GLBDhrNBbbFhxWaMfAFISE_fwlSm-TMGZfOy7l6uGEvv7_f27PE1DQzc1C3nJzw0jmE7TeZolnS2iw9DPOQcUHMshXZduMLVL8HTyOB1oxPybFjCCm67lUBYtkN8hAXaLur61DK8MyL06_TKIVzDAVxOmkvbEkaAjkgaMpfVwbx-LfAfWPqDB-pM3R01py-X3o6
Uploading the Artifact to the server...
Artifact uploaded to the demo server
Backend ready and running in the background. Press Enter to show the logs.
Press Ctrl-C to stop the backend and quit.
```

After:

```
Starting the Mender demo environment...
Creating network "integration_mender" with the default driver
Creating integration_mender-gui_1           ... done
Creating integration_mender-mongo_1         ... done
Creating integration_mender-elasticsearch_1 ... done
Creating integration_mender-redis_1         ... done
Creating integration_minio_1                ... done
Creating integration_mender-deployments_1   ... done
Creating integration_mender-useradm_1       ... done
Creating integration_mender-inventory_1     ... done
Creating integration_storage-proxy_1        ... done
Creating integration_mender-conductor_1     ... done
Creating integration_mender-device-auth_1   ... done
Creating integration_mender-api-gateway_1   ... done
Creating a new user...
****************************************

Username: mender-demo@example.com
Login password: 4PBOJF3Ah1Ja

****************************************
Please keep the password available, it will not be cached by the login script.
Mender demo server ready and running in the background. Copy credentials above and log in at https://localhost
Press Enter to show the logs.
Press Ctrl-C to stop the backend and quit.
```

### CODE REVIEW

**Comment by estenberg** [comment]
If this is acceptable we should backport to 2.1.x as well for final

**Comment by estenberg** [comment]
Some special side-effect of this PR is to be expected due to the assigned PR number. What is it? ;)

**Comment by kacf** [comment]
Haha, the devil is devious, this will probably fail, not now, but when we release it!

**Comment by kacf** [comment]
Cherry-picked [here](https://github.com/mendersoftware/integration/pull/667).

**Pull request merged**
