### PR TITLE
test: fix test_access.py

### PR DESCRIPTION
**Pull request by merlin-northern**
test: fix test_access.py

Ticket: QA-469
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please

**Comment by merlin-northern** [comment]
ignore for now -- I was recovering lost code.

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please sugar sugar

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please sugar sugar

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please sugar sugar

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast please sugar sugar

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast pretty sweet please sugar sugar

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast pretty sweet please sugar sugar

**Review by lluiscampos — APPROVED** [review]
Awesome work! Thank you

Nitpick: the last commit should say "test: ~re-enable and~ fix test_access.py"

**Comment by merlin-northern** [comment]
> Nitpick: the last commit should say "test: ~re-enable and~ fix test_access.py"
fixed.

**Comment by merlin-northern** [comment]
not rerunning the pipeline as the last push was no diff.

**Comment by merlin-northern** [comment]
@mender-test-bot  cherry-pick to:
 * 3.4.x
 * 3.3.x

**Pull request merged**
