### PR TITLE
Update staging

### PR DESCRIPTION
**Pull request by lluiscampos**
The motivation is to bring #1240 to staging before scheduled run next week

### CODE REVIEW

**Comment by lluiscampos** [comment]
However, my run from `integration/master` to HM staging revealed test failures (see [here](https://gitlab.com/Northern.tech/Mender/integration/-/jobs/1069384700)), so I guess to get them green we would need to update staging.

In any case better to run the tests with some known failures than not be able to run the tests at all.

**Comment by lluiscampos** [comment]
@mender-test-bot yes please, start pipeline :man_dancing:

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline again

**Review by tranchitella — APPROVED** [review]

**Comment by lluiscampos** [comment]
Failing tests (from previous build) are:
* `test_session_recording` Latest stable client does not support it.
* `test_demo_artifact` Known unstable test.

**Pull request merged**
