### PR TITLE
chore: update dependencies to fix backend integration pipelines

### PR DESCRIPTION
**Pull request by merlin-northern**
fixing:
```
Collecting pytest-forked==1.4.0 (from -r /builds/Northern.tech/Mender/integration/tests/requirements/python-requirements.txt (line 14))
  Downloading pytest_forked-1.4.0-py3-none-any.whl (4.9 kB)
Collecting pytest-html==3.1.1 (from -r /builds/Northern.tech/Mender/integration/tests/requirements/python-requirements.txt (line 15))
  Downloading pytest_html-3.1.1-py3-none-any.whl (14 kB)
ERROR: Ignored the following versions that require a different python version: 2.0.1 Requires-Python >=3.7.0,<3.11.0
ERROR: Could not find a version that satisfies the requirement pytest-metadata==2.0.1 (from versions: 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 2.0.0, 2.0.2, 2.0.3, 2.0.4, 3.0.0)
ERROR: No matching distribution found for pytest-metadata==2.0.1
```
ref:
 https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/4729413295

Ticket: None

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please baby

**Review by oldgiova — APPROVED** [review]

**Comment by merlin-northern** [comment]
@oldgiova let's merge yours (https://github.com/mendersoftware/integration/pull/2402) and I will close this one.

**Comment by oldgiova** [comment]
> @oldgiova let's merge yours (#2402) and I will close this one.

ok! Mine is still running though

**Comment by merlin-northern** [comment]
this one went with https://github.com/mendersoftware/integration/pull/2402

**Pull request closed without merging**
