### PR TITLE
build(docker-client): Add support for building the cpp-client

### PR DESCRIPTION
**Pull request by oleorhagen**
Ticket: MEN-5796

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]

**Comment by oleorhagen** [comment]
`build:client-docker` passed. Merging.

**Comment by lluiscampos** [comment]
@oleorhagen This broke the image, as the install targets don't work as you expect. See discussion [here](https://northern-tech.slack.com/archives/C2D3HRU9M/p1672760537679349) and suggested fix at:
* https://github.com/mendersoftware/mender/pull/1113

**Comment by oleorhagen** [comment]
> @oleorhagen This broke the image, as the install targets don't work as you expect. See discussion [here](https://northern-tech.slack.com/archives/C2D3HRU9M/p1672760537679349) and suggested fix at:
> 
>     * [chore: Respect `prefix` in Makefile mender#1113](https://github.com/mendersoftware/mender/pull/1113)

Hah, we're we caught cheating #2054 

I'm sorry, I should have caught this. But it ran the build just fine, so I wasn't expecting any issues.

**Comment by mzedel** [comment]
> Hah, we're we caught cheating #2054 

Nope, you broke the GUI e2e tests - your canary in the client mine... 😅

**Pull request merged**
