### PR TITLE
MEN-4831: add HAVE_MONITOR to `gui` when running the monitor add-on

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Review by merlin-northern — APPROVED** [review]
lgtm

**Comment by tranchitella** [comment]
Combined QA pipeline with https://github.com/mendersoftware/tenantadm/pull/316:
https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/348292116

**Comment by tranchitella** [comment]
Failure in `tests/test_mtls.py::TestClientMTLSEnterprise::test_mtls_enterprise_without_client_cert` is not related.

**Pull request merged**
