### PR TITLE
allowed access to qemu container from localhost through port 3000

### PR DESCRIPTION
**Pull request by mzedel**
Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by lluiscampos** [comment]
The error in the test seems related to this change, we need to fix before merging/releasing

**Comment by mzedel** [comment]
yep, but according to the integration repository there should not be another exposed 3000... is there some jenkins config using 3000?

**Comment by lluiscampos** [comment]
A lot cleaner now.

@kacf Should we wait for the integ tests? Seeing the full change-set now, Not necessary IMO

**Comment by kacf** [comment]
This failed last time. I think we should wait, to be sure.

**Pull request merged**
