### PR TITLE
Traefik integration test follow-ups

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Review by kjaskiewiczz — APPROVED** [review]
looks good

**Review by tranchitella — APPROVED** [review]

**Comment by tranchitella** [comment]
@alfrunes let's merge this (as it fixes the demo artifact failures) and see what happens :)

**Pull request merged**
