### PR TITLE
3.0.x fix tests dependencies

### PR DESCRIPTION
**Pull request by kjaskiewiczz**
Remove indirect dependencies from requirements.txt

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Review by kacf — APPROVED** [review]

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr mender-artifact/415

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr mender-artifact/415

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr mender-artifact/415

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr mender-artifact/415

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr mender-artifact/415

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr mender-artifact/415

**Pull request closed without merging**
