### PR TITLE
paramiko:allow_agent set to false

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline sugar pretty please

**Comment by merlin-northern** [comment]
@tranchitella the same instability as mentioned in [this comment](https://github.com/mendersoftware/integration/pull/1328#discussion_r619590887) and addressed in [integration/pull/1328](https://github.com/mendersoftware/integration/pull/1328) showed itself here: https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/1208933403

**Review by tranchitella — APPROVED** [review]

**Comment by tranchitella** [comment]
@merlin-northern I believe it is the circuit breaker in Traefik. Please don't merge this PR, let's wait for @lluiscampos's review.

**Comment by merlin-northern** [comment]
> @merlin-northern I believe it is the circuit breaker in Traefik. Please don't merge this PR, let's wait for @lluiscampos's review.

you mean the 503? (they are not related to this PR, they appear now-and-then)

**Comment by lluiscampos** [comment]
I thought #1333 would be enough. Not sure if disabling the agent completely is a good idea, it might be in use in other repos that re-use the integration test framework

**Review by lluiscampos — APPROVED** [review]

**Comment by merlin-northern** [comment]
wow, I have not closed this PR! how can it close by itself?

**Comment by merlin-northern** [comment]
> wow, I have not closed this PR! how can it close by itself?

recreated here, has anyone have any idea hy github closes the PRs automaticaly?

**Pull request closed without merging**
