### PR TITLE
test: Work around device name change in kirkstone.

### PR DESCRIPTION
**Pull request by kacf**
Since we are upgrading from a previous Yocto image, we need to jump
through some hoops to change the device name as part of the upgrade.

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
* Dunfell pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/565501322
* Kirkstone pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/565510487

**Review by oleorhagen — APPROVED** [review]

**Review by oleorhagen — APPROVED** [review]

**Comment by kacf** [comment]
@oleorhagen: FYI. I had to add some more build host workarounds, probably related to what you're doing.

**Comment by kacf** [comment]
And I just keep spewing out good commit messages these days! 😉

**Comment by oleorhagen** [comment]
> And I just keep spewing out good commit messages these days! wink

Someone has taught you well! :laughing:

**Comment by kacf** [comment]
* Dunfell pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/580158532
* Kirkstone pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/579484998

**Pull request merged**
