### PR TITLE
release_tool: Add -b option to start builds of Mender versions. 

### PR DESCRIPTION
**Pull request by kacf**
Changelog: None

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
@drewmoseley: Here is the update of the release_tool we talked about, to start builds of Mender with the right arguments. Maybe you wanna try it out before I merge, to make sure it solves your use case?

**Comment by drewmoseley** [comment]
@kacf how do I invoke this?  I merged your branch into mine and I get the following:

```
$ ./extra/release_tool.py -b 1.0.0                                                                                                                                                                                                                  
Fetching cached parameters from /home/dmoseley/.release-tool.yml. Delete to reset.
Traceback (most recent call last):
  File "./extra/release_tool.py", line 1433, in <module>
    main()
  File "./extra/release_tool.py", line 1424, in main
    do_build(args)
  File "./extra/release_tool.py", line 1061, in do_build
    version = version_of(integration_dir(), repo.container, args.build)
  File "./extra/release_tool.py", line 248, in version_of
    image = data['services'][repo_container]['image']
KeyError: 'mender-artifact'
```

```
$ ./extra/release_tool.py -b 1.0.1
Fetching cached parameters from /home/dmoseley/.release-tool.yml. Delete to reset.
Traceback (most recent call last):
  File "./extra/release_tool.py", line 1433, in <module>
    main()
  File "./extra/release_tool.py", line 1424, in main
    do_build(args)
  File "./extra/release_tool.py", line 1061, in do_build
    version = version_of(integration_dir(), repo.container, args.build)
  File "./extra/release_tool.py", line 248, in version_of
    image = data['services'][repo_container]['image']
KeyError: 'mender-artifact'
```

```
$ ./extra/release_tool.py -b 1.2.2
Fetching cached parameters from /home/dmoseley/.release-tool.yml. Delete to reset.
Traceback (most recent call last):
  File "./extra/release_tool.py", line 1433, in <module>
    main()
  File "./extra/release_tool.py", line 1424, in main
    do_build(args)
  File "./extra/release_tool.py", line 1071, in do_build
    trigger_jenkins_build(state, check_tag_availability(state))
  File "./extra/release_tool.py", line 485, in check_tag_availability
    capture=True, capture_stderr=True)
  File "./extra/release_tool.py", line 350, in execute_git
    os.chdir(git_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/work/dmoseley/Mender/integration/useradm'
```

What values can I use for the command line parameter?

How do I invoke this on a meta-mender PR (specifically https://github.com/mendersoftware/meta-mender/pull/412)? 

Will this allow me to manually test things such as https://github.com/mendersoftware/meta-mender/pull/412 and ignore or comment out the failing tests due to incompatibilities with the older versions?

**Comment by kacf** [comment]
> ```
> $ ./extra/release_tool.py -b 1.0.0                                                                                                                                                                                                                  
> Fetching cached parameters from /home/dmoseley/.release-tool.yml. Delete to reset.
> Traceback (most recent call last):
>   File "./extra/release_tool.py", line 1433, in <module>
>     main()
>   File "./extra/release_tool.py", line 1424, in main
>     do_build(args)
>   File "./extra/release_tool.py", line 1061, in do_build
>     version = version_of(integration_dir(), repo.container, args.build)
>   File "./extra/release_tool.py", line 248, in version_of
>     image = data['services'][repo_container]['image']
> KeyError: 'mender-artifact'
> ```

These are due to the fact that the 1.0.x series is too old. This could be worked around in theory, but is it necessary? This was the very first release that was only supported for a few months, and it's been out of support for months already.

Everything from 1.1.0 and onwards should not get that error.

> ```
> $ ./extra/release_tool.py -b 1.2.2
> Fetching cached parameters from /home/dmoseley/.release-tool.yml. Delete to reset.
> Traceback (most recent call last):
>   File "./extra/release_tool.py", line 1433, in <module>
>     main()
>   File "./extra/release_tool.py", line 1424, in main
>     do_build(args)
>   File "./extra/release_tool.py", line 1071, in do_build
>     trigger_jenkins_build(state, check_tag_availability(state))
>   File "./extra/release_tool.py", line 485, in check_tag_availability
>     capture=True, capture_stderr=True)
>   File "./extra/release_tool.py", line 350, in execute_git
>     os.chdir(git_dir)
> FileNotFoundError: [Errno 2] No such file or directory: '/work/dmoseley/Mender/integration/useradm'
> ```

Hmm, I can't reproduce this. Where are your non-integration repositories? Inside integration or outside on the same level as integration?

> What values can I use for the command line parameter?

Any valid tag from the integration repository. Each tag corresponds to an overall Mender version. You can change individual service versions as well, by saying no to start the build and then changing one or more of the parameters.

> How do I invoke this on a meta-mender PR (specifically mendersoftware/meta-mender#412)?

Yes, sorry if this wasn't completely apparent, I did this a bit quick and dirty, so it's mostly a minimized adaptation of the release menu. What happens once you get past the unexpected error above is that you get a menu of Jenkins parameters, and here you can change individual parameters, so that pull request would mean changing the `META_MENDER_REV` to `pull/412/head`, and probably some of the other parameters as well, to point to `morty`. Then you start the build using that. The parameters are cached in `~/.release-tool.yml` until you request a new version to build, so you can build it multiple times without having to input it every time.

I realize now that one feature is missing: It won't actually link the pull request to Github, so you won't see the little status marker, and have to keep track of the build number yourself. I'll try to add that as well, but let's keep this PR open so we can resolve the initial problems first.

> Will this allow me to manually test things such as mendersoftware/meta-mender#412 and ignore or comment out the failing tests due to incompatibilities with the older versions?

Sort of, but probably not the way you think. Once you build one specific overall Mender version, all service versions are matched with each other, and this combination is more or less guaranteed to work because it is what was tested for the release. But there is one exception, meta-mender, which is the only moving component. So a test inside `meta-mender/tests/acceptance` can still break. However, these are meant to be protected against such breakage by [markers such as these](https://github.com/drewmoseley/meta-mender/blob/fix-dtb-handling-morty/tests/acceptance/test_update.py#L128), so they should (in theory) never be run against the wrong version.

It is worth noting that the latest error you got in https://github.com/mendersoftware/meta-mender/pull/412, [this one](https://s3-eu-west-1.amazonaws.com/mender-acceptance-mmc-reports/3614/report.html), appears to be legitimate failure, that test should definitely pass, on all versions going back to 1.1.0. If it fails there may be a real bug in the build pipeline somewhere, maybe it's not picking up the right version of the mender-artifact tool? If you keep having trouble with this one, let me know, I can take a look.

**Comment by drewmoseley** [comment]
I don't need the 1.0.x support here so we can ignore that error.

> Hmm, I can't reproduce this. Where are your non-integration repositories? Inside integration or outside on the same level as integration?

I only have the integration repo checked out.  What is the git repo structure I am expected to have with this?

**Comment by kacf** [comment]
> I only have the integration repo checked out. What is the git repo structure I am expected to have with this?

Oh right, you need The Ten Repos™:

* deployments
* deviceadm
* deviceauth
* gui
* integration
* inventory
* mender
* mender-artifact
* mender-api-gateway-docker
* useradm

They should all be in the same directory.

It's strange though, the error you got is not what I would have expected if the repos are missing. Something I need to check out.

**Comment by drewmoseley** [comment]
OK.  After getting the repos all checked out I was able to kick off a build with the following config file
```
deployments: {version: 1.2.2}
deviceadm: {version: 1.1.0}
deviceauth: {version: 1.2.0}
extra_buildparams: {BUILD_BBB: 'off', BUILD_QEMU: 'on', BUILD_QEMU_RAW_FLASH: 'off',
  BUILD_RPI3: 'off', CLEAN_BUILD_CACHE: '', MENDER_QA_REV: master, MENDER_STRESS_TEST_CLIENT_REV: master,
  META_MENDER_REV: pull/412/head, META_OPENEMBEDDED_REV: morty, META_RASPBERRYPI_REV: morty,
  POKY_REV: morty, PUSH_CONTAINERS: 'off', RUN_INTEGRATION_TESTS: 'on', TENANTADM_REV: master,
  TESTS_IN_PARALLEL: '8', TEST_BBB: '', TEST_QEMU: 'on', TEST_RPI3: 'off', UPLOAD_OUTPUT: ''}
gui: {version: 1.2.1}
integration: {version: 1.2.2}
inventory: {version: 1.1.0}
mender: {version: 1.2.1}
mender-api-gateway-docker: {version: 1.2.1}
mender-artifact: {version: 2.1.1}
repo_dir: /work/dmoseley/Mender/sources/mender-dev
useradm: {version: 1.2.0}
version: 1.2.2
```

The results are here: https://mender-jenkins.mender.io/job/mender-builder/3635/

Not sure why the build failed with a license checksum mismatch since that doesn't happen when I build locally or when the build from my PR itself is run.  I assume it's something in the build system handling of mender checkouts using the EXTERNALSRC stuff.

**Comment by kacf** [comment]
Merging this, but I will try to improve on some of the shortcomings later.

**Pull request merged**
