### PR TITLE
added circuitbreaker middleware to prevent accumulating buffered requests

### PR DESCRIPTION
**Pull request by mzedel**
- this is in light of the behaviour we saw during the scale testing
=> https://doc.traefik.io/traefik/middlewares/circuitbreaker/ for reference

Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Comment by mzedel** [comment]
> @mzedel, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".
@mender-test-bot and a chocolate bar please!

**Comment by alfrunes** [comment]
>     * this is in light of the behaviour we saw during the scale testing
>    ....

Sorry, I need some more context - what behavior?

**Comment by tranchitella** [comment]
> > @mzedel, Let me know if you want to start the integration pipeline by mentioning me and the command "something".
> 
> @mender-test-bot and a chocolate bar please!

@mzedel @lluiscampos this is getting a bit out of control.... :-p

**Comment by mzedel** [comment]
> Sorry, I need some more context - what behavior?

The increasing memory consumption of traefik when a downstream service (e.g. deployments) dies and traefik buffers all the requests to that service... with the circuit breakers the buffering should be stopped as soon as either 25% of the requests return with a response code in [500..599] or more than 10% of the requests return with a network error (the thresholds might need some adjustments...)

considering your investigations into that issue I thought you might be interested to try to reproduce the bad behaviour with these in place and I hope you won't be able to 😅

**Comment by lluiscampos** [comment]
> > ```
> > * this is in light of the behaviour we saw during the scale testing
> > ```
> > 
> > 
> > ....
> 
> Sorry, I need some more context - what behavior?

See also [MEN-4642](https://tracker.mender.io/browse/MEN-4642).

**Comment by alfrunes** [comment]
I missed the context around these escalations in memory consumption and thought it in general was proportional to the number of connections being proxied to the backend. Thanks for clearing it up, it makes a lot more sense now.

**Review by lluiscampos — APPROVED** [review]
By reading the docs this change looks good to me :+1: 

For next Scale Testing iteration we can port it to production manifests and simulate again high loads.

**Pull request merged**
