### PR TITLE
chore: migrated smtpd to aiosmtpd

### PR DESCRIPTION
**Pull request by kjaskiewiczz**
Smtpd is fully removed in python3.12.
Moved from smtpd and asyncore to aiosmtpd.

Ticket: QA-603

Signed-off-by: Daniel Skinstad Drabitzius <daniel.drabitzius@northern.tech>
(cherry picked from commit 27c42dbf155d65e1dd8383dcad9235e33395bd3c)

### CODE REVIEW

**Review by kacf — APPROVED** [review]

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr useradm-enterprise/840

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr useradm-enterprise/840

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr useradm-enterprise/840

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline --pr useradm-enterprise/840

**Pull request merged**
