### PR TITLE
fix: Mark test_test_regular_protocol_commands as flaky with max runs 3.

### PR DESCRIPTION
**Pull request by merlin-northern**
Changelog: Title
Ticket: QA-504
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline sugar pretty please

**Review by lluiscampos — APPROVED** [review]
Good comment, thanks for that.

But please remove the Changelog entry from the commit

**Comment by merlin-northern** [comment]
> Good comment, thanks for that.
> 
> But please remove the Changelog entry from the commit

argh :) sorry. removed.
I wonder about the policy on change log entries in the integration repo?

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline sugar pretty please
wow, I actually missed one line. sorry for that.

**Comment by merlin-northern** [comment]
only a known failure with stopping the composition.

**Comment by merlin-northern** [comment]
@mender-test-bot cherry-pick to:
 * 3.4.x
please and Merry Christmas

**Comment by merlin-northern** [comment]
cherry-pick to:
 * 3.3.x

**Comment by merlin-northern** [comment]
@mender-test-bot cherry-pick to:
 * 3.3.x
please

**Pull request merged**
