### PR TITLE
test_api_endpoints.py: Add devicemonitor endpoints to the test

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@tranchitella Is this the right thing to do? What about adding a note in [adding-new-repo documentation](https://github.com/mendersoftware/mender-qa/blob/master/Documentation/adding-new-repository.md) for future repos?

**Comment by lluiscampos** [comment]
Note: I am not running the pipeline as this test can only be executed once it hits master.

**Comment by lluiscampos** [comment]
@mender-test-bot please start pipeline

**Comment by tranchitella** [comment]
> @tranchitella Is this the right thing to do? What about adding a note in [adding-new-repo documentation](https://github.com/mendersoftware/mender-qa/blob/master/Documentation/adding-new-repository.md) for future repos?

The note is there: https://github.com/mendersoftware/mender-qa/blob/master/Documentation/adding-new-repository.md#integration
Yes, your change is correct.

**Review by tranchitella — APPROVED** [review]

**Comment by lluiscampos** [comment]
> The note is there: https://github.com/mendersoftware/mender-qa/blob/master/Documentation/adding-new-repository.md#integration

Sorry, I didn't even read that :see_no_evil: I was surprised that we missed `devicemonitor` and `reporting` (the latter I'll add in a separate PR).

**Comment by lluiscampos** [comment]
The enterprise test passed in [the previous run](https://gitlab.com/Northern.tech/Mender/mender-qa/-/jobs/1595331277). Merging.

**Pull request merged**
