### PR TITLE
MEN-5336 Monitoring test: remove old alerts from the store.

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --pr monitor-client/104 --pr integration/1849

**Comment by oleorhagen** [comment]
Discussed f2f, and decided an integration test is probably not needed here, considering the functionality is freestanding (not tied to interacting with any external components).

**Review by lluiscampos — CHANGES_REQUESTED** [review]
Please remove the changelog entry - tests do not honor a changelog entry.

**Comment by merlin-northern** [comment]
> Please remove the changelog entry - tests do not honor a changelog entry.

it is only in the description in here (github), the commit does not have the changelog. right now I am trying to debug, so there is an additional commit. I learned the change logs already :)

**Comment by merlin-northern** [comment]
> Discussed f2f, and decided an integration test is probably not needed here, considering the functionality is freestanding (not tied to interacting with any external components).

correct. however, since we already have the test and it is passing, perhaps we can keep it?

**Review by oleorhagen — APPROVED** [review]
Sure, let's just get this merged

**Comment by merlin-northern** [comment]
last push: only [licence copyright year increment](https://github.com/mendersoftware/integration/compare/a48458afef0260b97350b1786c4bfb2a585c50ea..eaae0c1ebdcb7dc589491a89a571ae2553cabeff).

**Comment by merlin-northern** [comment]
pipeline together with https://github.com/mendersoftware/monitor-client/pull/104: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/446831620

**Pull request merged**
