### PR TITLE
aligned demo server location with the default demo server 

### PR DESCRIPTION
**Pull request by mzedel**
...that's used in other parts of the setup (client/ connect/ ui)

I hope that's not problematic in any other area

Changelog: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

### CODE REVIEW

**Review by kacf — APPROVED** [review]

**Review by tranchitella — APPROVED** [review]

**Review by lluiscampos — COMMENTED** [review]
I think this is incorrect: `MENDER_SERVER_URI` variable is only used within the script (iow local workstation!) to create the user or upload the artifact. If we change it to docker.mender.io, then we would need to ask users to modify their `/etc/hosts` to set this url to `localhost`. (does this make sense?)

**Comment by lluiscampos** [comment]
Both @kacf and @tranchitella approving makes me believe I am missing something...

**Review by tranchitella — CHANGES_REQUESTED** [review]
Actually @lluiscampos is right, and I didn't notice it because I have docker.mender.io in my /etc/hosts. Without it, the demo server, OS version doesn't start.

**Comment by mzedel** [comment]
hm too bad, I too forgot about the hosts file change... sadly it seems to only be possible to get rid of the requirement in the demo script but not running the under the correct location... much disappoint 😞

**Pull request closed without merging**
