### PR TITLE
test: last checkin backend test.

### PR DESCRIPTION
**Pull request by merlin-northern**
Ticket: MEN-6381

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast --pass please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast --pass please

**Review by kjaskiewiczz — COMMENTED** [review]
the test looks good, but it duplicates quite a lot of functions from the test_reporting.py
I'd either put the test inside test_reporting.py or move some methods to common part

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast --pass please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast --pass please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast --pass please

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline --fast --pass please

**Review by kjaskiewiczz — APPROVED** [review]
looks good; thanks!

**Comment by merlin-northern** [comment]
> looks good; thanks!

thank you for the review

**Pull request merged**
