### PR TITLE
2.6.x: Regenerate crypto materials for mTLS testing using a script

### PR DESCRIPTION
**Pull request by lluiscampos**
Porting #1424.

### CODE REVIEW

**Comment by lluiscampos** [comment]
> @lluiscampos, Let me know if you want to start the integration pipeline by mentioning me and the command "start pipeline".

@mender-test-bot :ping_pong:

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@lluiscampos Now you'll also need b7235dc8a922b786b7df60dc4161b60f1d2dab8d once #1445 is merged

**Comment by lluiscampos** [comment]
> @lluiscampos Now you'll also need [b7235dc](https://github.com/mendersoftware/integration/commit/b7235dc8a922b786b7df60dc4161b60f1d2dab8d) once #1445 is merged

No, because integration 2.6.x should be testing mtls-ambassador 1.0.x (which is what I am fixing now)

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
