### PR TITLE
allow access to https://localhost in test environment

### PR DESCRIPTION
**Pull request by estenberg**
Ref discussion in https://github.com/mendersoftware/integration/pull/320

### CODE REVIEW

**Comment by GregorioDiStefano** [comment]
Tests are failing here because this now fails: https://github.com/mendersoftware/integration/blob/master/tests/run.sh#L80

**Comment by estenberg** [comment]
@GregorioDiStefano thanks, is this an appropriate fix?

**Comment by estenberg** [comment]
Chery-picked to 1.2.x in 1dc2db336b2b7bce2085dce8c135711986e0555a

**Comment by estenberg** [comment]
Docs update: https://github.com/mendersoftware/mender-docs/pull/204

**Pull request merged**
