### PR TITLE
FIX: Broken imports in test_tenantadm.py

### PR DESCRIPTION
**Pull request by alfrunes**
Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

### CODE REVIEW

**Comment by lluiscampos** [comment]
The Pipeline will fail, master build is broken at the moment. We are fixing it in https://github.com/mendersoftware/mender-qa/pull/312

**Comment by alfrunes** [comment]
@lluiscampos There are some broken imports here as well. (See diff)

**Comment by lluiscampos** [comment]
> @lluiscampos There are some broken imports here as well. (See diff)

I know. But without the other fix it will not even be able to start the job

**Comment by lluiscampos** [comment]
New pipeline started: https://gitlab.com/Northern.tech/Mender/mender-qa/pipelines/86250153

**Comment by alfrunes** [comment]
ohh, thanks for the heads up!
I think we can merge this one either way. Unless there are more stuff that needs fixing on the master branch.

**Comment by lluiscampos** [comment]
New build: https://gitlab.com/Northern.tech/Mender/mender-qa/pipelines/86264859

**Comment by lluiscampos** [comment]
The failure is due to the pytest version. I have a fix ready that I will submit in a different PR.

**Comment by lluiscampos** [comment]
See PR #707

**Pull request merged**
